### ISSUE TITLE
[Bug] CPU utilisation is overshooting in Synology NAS

### ISSUE THREAD

**Issue by mahdihijazi** [MauriceNino/dashdot#1086]
### Description of the bug

I could never get the CPU usage to match what Synology NAS is showing me. I am not quite sure if my expectation that they should match is accurate. If it is, then something is going wrong.

![Screenshot 2024-12-31 at 12 13 20](https://github.com/user-attachments/assets/d8a1222e-28b8-40f7-8309-313beb37ff70)

### How to reproduce

my docker-compose file:

```
version: "3.5"

services:
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped
    privileged: true
    ports:
      - "3001:3001" 
    volumes:
      - /volume1/homelab/dashdot:/mnt/host:ro 
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: "true" 
      DASHDOT_CPU_TEMPS_MODE: "avg" 
      DASHDOT_CPU_CORES_TOGGLE_MODE: "toggle" 
      DASHDOT_CPU_POLL_INTERVAL: "2000" 
      DASHDOT_CPU_SHOWN_DATAPOINTS: "30" 
      DASHDOT_WIDGET_LIST: "os,cpu,storage,ram,network" 
      DASHDOT_OVERRIDE_OS: "DSM"
```

### Info output of dashdot cli

```shell
INFO
=========
Yarn: 3.7.0
Node: v20.17.0
Dash: 5.9.0

Cwd: /app
Hash: 696233f6378f4af6c45bf88144dcec4edb38f8ba
Platform: Linux f0100aaaeb2f 4.4.302+ #72806 SMP Thu Sep 5 13:41:01 CST 2024 x86_64 GNU/Linux
Docker image: base
In Docker: true
In Docker (env): true
In Podman: false
```

### Where is your instance running?

Other (Please specify below)
