### ISSUE TITLE
[Bug] Wrong OS reporting

### ISSUE THREAD

**Issue by FaNt4zMa** [MauriceNino/dashdot#1168]
### Description of the bug

I just recently realized that dashdot is displaying Alpine Linux 24.04 as my OS when its in fact Ubuntu 24.04. When binding the /etc/os-release and redeploying I get the correct OS but it doesn't persist after a system/docker reboot. Was the dashdot image always alpine based?

![Image](https://github.com/user-attachments/assets/5be519db-6b6b-45c8-bba2-0ab096c147ab)

![Image](https://github.com/user-attachments/assets/0d8dea5e-6577-417f-bca5-a8eee461fbff)

### How to reproduce

Uh, deploy Dashdot on a ubuntu machine? Sorry there's not much to reproduce as that wasn't an issue before. It must have happen after watchtower auto updated it. Here's my docker compose if that helps:
```
services:
    dash:
        image: mauricenino/dashdot:latest
        container_name: dash
        privileged: true
        volumes:
            - /:/mnt/host:ro
            - /etc/os-release:/etc/os-release:ro
#            - /proc/1/ns/net:/mnt/host_ns_net:ro
        ports:
            - 8081:3001
        env_file: stack.env
        environment:
            - DASHDOT_WIDGET_LIST=os,cpu,ram,network,storage
            - DASHDOT_PAGE_TITLE=Server Status
            - DASHDOT_SHOW_DASH_VERSION=icon_hover
            - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
            - DASHDOT_SHOW_HOST=true
            - DASHDOT_CUSTOM_HOST=Ultron
            - DASHDOT_ENABLE_CPU_TEMPS=true
            - DASHDOT_CPU_POLL_INTERVAL=2000
            - DASHDOT_ACCEPT_OOKLA_EULA=true
            - DASHDOT_SPEED_TEST_INTERVAL=720
        restart: unless-stopped
```

### Relevant log output

```shell

```

### Info output of dashdot cli

```shell
INFO
=========
Yarn: 3.7.0
Node: v20.19.0
Dash: 5.9.2

Cwd: /app
Hash: 14ed9f1a30782eedb43c048aacd81ed93cb1d467
Platform: Linux 6594d65d30e6 6.8.0-56-generic #58-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 14 15:33:28 UTC 2025 x86_64 GNU/Linux
Docker image: base
In Docker: true
In Docker (env): true
In Podman: false
```

### Where is your instance running?

Desktop PC (Linux)

**Comment by 5calV** [comment]
Same here, dashdot is displaying Alpine Linux 24.04, running on a Debian Bookworm host.

**Comment by 5calV** [comment]
oh sprry, thank you

**Comment by 5calV** [comment]
dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_PAGE_TITLE: "TESTTITLE"
      DASHDOT_SHOW_DASH_VERSION: "none"
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
      DASHDOT_SPEED_TEST_INTERVAL: '30'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
    ports:
      - '3001:3001'
    volumes:
      - /etc/os-release:/etc/os-release:ro
      - /:/mnt/host:ro 
     

This did not work for me sadly.

**Comment by 5calV** [comment]
DASHDOT_OVERRIDE_OS also does not work for me, or am I doing something wrong?

  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_OVERRIDE_OS: 'Debian 12 Bookworm'
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_PAGE_TITLE: "TEST"
      DASHDOT_SHOW_DASH_VERSION: "none"
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
      DASHDOT_SPEED_TEST_INTERVAL: '30'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
    ports:
      - '3001:3001'
    volumes:
      - /:/mnt/host:ro

**Comment by FaNt4zMa** [comment]
@5calV If thats your actual Docker compose then yes, you need an hyphen before your environment, and also proper indentation maybe..? It should look like:
```
dash:
  image: mauricenino/dashdot:latest
  restart: unless-stopped
  privileged: true
  environment:
    - DASHDOT_ENABLE_CPU_TEMPS: 'true'
    - DASHDOT_PAGE_TITLE: "TESTTITLE"
    - DASHDOT_SHOW_DASH_VERSION: "none"
    - DASHDOT_SHOW_HOST: 'true'
    - DASHDOT_ACCEPT_OOKLA_EULA: 'true'
    - DASHDOT_SPEED_TEST_INTERVAL: '30'
    - DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
  ports:
    - '3001:3001'
  volumes:
    - /etc/os-release:/etc/os-release:ro
    - /:/mnt/host:ro
```

**Comment by 5calV** [comment]
The wrong indentation came from pasting it into here, my indentation is right.
I will just go for temporarily using DASHDOT_OS_OVERRIDE.

**Comment by MauriceNino** [comment]
I can confirm that this is also happening on the [public demo](https://dash.mauz.dev/), which is hosted on an Ubuntu host and shows Alpine right now. So this is definitely an issue I will have to look into.

Aside from that, I see a bunch of misconfigured compose files in this issue, so I just want to clear up, that the only mount needed, is `/:/mnt/host:ro` and I would ask you to remove all the others to make sure that bugs won't happen due to this.

```yaml
services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '80:3001'
    volumes:
      - /:/mnt/host:ro
```
