### ISSUE TITLE
Speedtest does not work

### ISSUE THREAD

**Issue by byte21516** [MauriceNino/dashdot#1186]
It showed the exact same numbers for a few days, didnt perform a speedtest for about 2 days.
After restarting the container it shows "/" the whole time.

![Image](https://github.com/user-attachments/assets/ced145ea-10ab-46af-bcc6-640c940e47c1)

My docker-compose (running on a Debian 12 Stable host):

```
services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      # Only use if wrong OS is being displayed:
      #DASHDOT_OVERRIDE_OS: 'TEST'
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_PAGE_TITLE: "MY_NAME"
      DASHDOT_SHOW_DASH_VERSION: "none"
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
      DASHDOT_SPEED_TEST_INTERVAL: '30'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
    ports:
      - '3001:3001'
    volumes:
      - /:/mnt/host:ro
```
