### ISSUE TITLE
Storage info incorrect

### ISSUE THREAD

**Issue by Just5KY** [MauriceNino/dashdot#14]
Running this on Pi4
Built an image for arm64

`docker build -t justsky/dashdot .`
https://hub.docker.com/r/justsky/dashdot

Compose
```
version: "3"
services:
  dashdot:
    container_name: dashdot
    image: justsky/dashdot
    ports:
      - 4002:3001
```
Log
```
    today at 3:21:49 PMyarn run v1.22.17
    today at 3:21:49 PM$ (cd ./backend && yarn start)
    today at 3:21:51 PM$ node .
    today at 3:21:52 PMlistening on *:3001
    today at 3:22:01 PMStatic Server Info Gathered:  {
    today at 3:22:01 PM  os: {
    today at 3:22:01 PM    arch: 'arm64',
    today at 3:22:01 PM    distro: 'Alpine Linux',
    today at 3:22:01 PM    kernel: '5.10.92-v8+',
    today at 3:22:01 PM    platform: 'linux',
    today at 3:22:01 PM    release: '3.15.0'
    today at 3:22:01 PM  },
    today at 3:22:01 PM  cpu: {
    today at 3:22:01 PM    manufacturer: 'Cortex-A72',
    today at 3:22:01 PM    brand: '',
    today at 3:22:01 PM    speed: 1.6,
    today at 3:22:01 PM    cores: 4,
    today at 3:22:01 PM    threads: 4
    today at 3:22:01 PM  },
    today at 3:22:01 PM  ram: { total: 8004149248, layout: [ [Object] ] },
    today at 3:22:01 PM  storage: { layout: [] }
    today at 3:22:01 PM}
```

I have 240GB ssd and 1TB hard disk, its not displaying storage info correctly

![image](https://user-images.githubusercontent.com/71321862/154659774-a4501d46-dcee-4832-a4b6-26af58d9cfad.png)

**Comment by Just5KY** [comment]
Sorry, I don't know anything about NextJS, @MauriceNino 
but,
I think you can pass hardware info using docker itself like how [linuxserver/scrutiny](https://hub.docker.com/r/linuxserver/scrutiny) has done for HardDisk S.M.A.R.T monitoring.

```yml
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    volumes:
      - /run/udev:/run/udev:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/nvme1n1:/dev/nvme1n1
```

**Comment by MauriceNino** [comment]
Thank you for that pointer! 
That looks really promising & I will look into that in the following days. 

In the meanwhile, I have pushed an update yesterday, that at least allows to read the available space of the running container and shows a graph for that. Not perfect, but better than before :)

**Comment by Just5KY** [comment]
yea I am downloading the arm64 image right now

**Comment by MauriceNino** [comment]
Huh, did not expect that. Can you maybe show me the command that you used to run this? Did you mount any devices?

**Comment by Just5KY** [comment]
as my Initial post 
I'm using 240GB SSD and 1TB hard disk.

This is my compose 
```yml
  dashdot:
    container_name: dashdot
    image: justsky/dashdot
    restart: unless-stopped
    ports:
      - 4002:3001
#    environment:
#      - DASHDOT_PORT=4003
```

**Comment by MauriceNino** [comment]
Thank you for all your input. I will have a look if I can make the type & name show up correctly.

On a sidenote: my experience with docker is very limited, but is there any problem with the image published by me, or is there another reason that you build your own?

**Comment by MauriceNino** [comment]
Would you mind opening up another issue with all the info you have on the topic? I will try to add this to my project, to support ARM too.

**Comment by Just5KY** [comment]
I opened #22 for github actions, then i saw you are doing it with Drone.
i think you just need to add docker buildx and QEMU then you can build multi-arch images in your Drone CI itself.

```sh
docker buildx create --use
docker buildx build --push --platform linux/amd/64,linux/arm64/v8  --tag justsky/dashdot .
```

Not sure if i should open another issue for this too but
Can you make it so that it shows seprate storage capacity too

```css
  storage: {
    layout: [
      { size: 1000204883968, type: 'HD', name: 'External USB 3.0' },
      { size: 240057407488, type: 'HD', name: 'high speed      ' }
    ]
  }
```

![image](https://user-images.githubusercontent.com/71321862/164554204-2ab6ac85-e918-457b-a0fe-6110081a6f23.png)
