### ISSUE TITLE
[Bug] Hostname does not display

### ISSUE THREAD

**Issue by JesseWebDotCom** [MauriceNino/dashdot#185]
### Description of the bug

Host name does not display (name=fsociety) even though environment variable is specified and log lists show_host as true
<img width="461" alt="Screen Shot 2022-07-06 at 9 07 36 PM" src="https://user-images.githubusercontent.com/20848952/177668212-71de2846-bb3f-4ab3-a018-9a8192f435e4.png">
.

### How to reproduce

Build using docker compose:
```
version: '3.8'

services:
  # https://github.com/MauriceNino/dashdot
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    privileged: true
    hostname: dash
    ports:
      - '3001:3001'
    volumes:
      - /:/mnt/host:ro    
    networks:
      - shared      
    environment: 
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_USE_IMPERIAL=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_ACCEPT_OOKLA_EULA=true
      - DASHDOT_NETWORK_LABEL_LIST=type,speed_up,speed_down,interface_speed,public_ip
    restart: unless-stopped   
```

### Relevant log output

```shell
fs_type_filter: [],
    disable_integrations: false,
    show_host: true,
    use_imperial: true,
    enable_storage_split_view: true,
    always_show_percentages: true,
    widget_list: [ 'os', 'cpu', 'storage', 'ram', 'network' ],
    os_label_list: [ 'os', 'arch', 'up_since' ],
    cpu_label_list: [ 'brand', 'model', 'cores', 'threads', 'frequency' ],
    storage_label_list: [ 'brand', 'size', 'type', 'raid' ],
    ram_label_list: [ 'brand', 'size', 'type', 'frequency' ],
    network_label_list: [
      'type',
      'speed_up',
      'speed_down',
      'interface_speed',
      'public_ip'
    ],
```

### Info output of dashdot cli

```shell
yarn run v1.22.19
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.4.0
Dash: 4.1.0

Cwd: /app
Hash: 13780583fe2f82e1c423d318bda482dde2ddee19
In Docker: true
In Podman: false
In Docker (env): true
```

### What browsers are you seeing the problem on?

Chrome, Safari

### Where is your instance running?

Desktop PC (Linux)

### Additional context

Great job, thanks for this project.
