### ISSUE TITLE
[Bug] Not showing storage usage of second drive

### ISSUE THREAD

**Issue by fidst** [MauriceNino/dashdot#493]
### Description of the bug

dash is not showing any usage of my second drive
![image](https://user-images.githubusercontent.com/9792886/207908336-a77db904-93d5-4d55-9867-22dfa4726bf8.png)

```
dashdot:
    container_name: dashdot
    hostname: dashdot
    image: mauricenino/dashdot:latest
    ports:
      - '8002:3001'
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: "true"
      DASHDOT_SHOW_HOST: "true"
      DASHDOT_ACCEPT_OOKLA_EULA: "true"
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: "true"
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: "true"
      DASHDOT_PAGE_TITLE: "Manor.Dash"
      #DASHDOT_WIDGET_LIST: os,cpu,gpu,storage,ram,network
      DASHDOT_NETWORK_LABEL_LIST: type,speed_up,speed_down,interface_speed,public_ip
    volumes:
      - '/media/sam1tb/:/mnt/sam:ro'`
```

### Relevant log output

```shell
docker exec dashdot df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 215.5G     77.1G    127.3G  38% /
tmpfs                    64.0M         0     64.0M   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/sdb                915.8G    807.7G     61.5G  93% /mnt/sam
/dev/mapper/ubuntu--vg-ubuntu--lv
                        215.5G     77.1G    127.3G  38% /mnt/host_mnt
/dev/mapper/ubuntu--vg-ubuntu--lv
                        215.5G     77.1G    127.3G  38% /etc/resolv.conf
/dev/mapper/ubuntu--vg-ubuntu--lv
                        215.5G     77.1G    127.3G  38% /etc/hostname
/dev/mapper/ubuntu--vg-ubuntu--lv
                        215.5G     77.1G    127.3G  38% /etc/hosts
```

### Info output of dashdot cli

```shell
yarn run v1.22.19
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.12.1
Dash: 4.5.7

Cwd: /app
Hash: afb9e0fcb3b1bad8ba684b751596d4a56c9e1dfc
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.36s.
```

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Linux Server

### Additional context

Running ubuntu server.
I have the samsung SSH added via fstab. If there is a better way, let me know.
