### ISSUE TITLE
[Bug] Disk usage over 100%

### ISSUE THREAD

**Issue by enrico1203** [MauriceNino/dashdot#514]
### Description of the bug

Real disk space avaliable: 
![image](https://user-images.githubusercontent.com/61981530/210274460-b559939e-657a-4839-a8da-47a977a14030.png)
what i see on dash.:
![Immagine 2023-01-02 210653](https://user-images.githubusercontent.com/61981530/210274485-31626fbe-b864-4ff5-b55e-a280a41edd6a.png)

### How to reproduce

i'm using docker compose. 

```yml
version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_FS_VIRTUAL_MOUNTS: 'db-ita-crypt:/'
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: 'true'
    volumes:
      - /:/mnt/host:ro
      - /proc/1/ns/net:/mnt/host_ns_net:ro
    ports:
      - '80:3001'
```

### Info output of dashdot cli

```shell
docker exec dash-dash-1 yarn cli info
yarn run v1.22.19
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.12.1
Dash: 4.6.0

Cwd: /app
Hash: 68a114ef96f399acb69125364a744840b30c16d9
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.20s.
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Where is your instance running?

Linux Server
