### ISSUE TITLE
[Feature] Add Support for BTRFS Multi drive Devices (like RAID)

### ISSUE THREAD

**Issue by PlexSheep** [MauriceNino/dashdot#602]
### Description of the feature

BTRFS has a special Multi device functionality, like raid. My Homeserver has 3 drives working together to create something like a RAID1 array, all data is stored twice accross all devices, if one breaks all data can be restored.

In short it looks like this:
```
plex@homeserver /srv % doas btrfs filesystem show .
doas (plex@homeserver) password: 
Label: 'RAID1 ARRAY BTRFS main data of homeserver'  uuid: 59765ea5-e3b7-4ba2-b7b1-19acc65bc6ca
        Total devices 3 FS bytes used 1.05TiB
        devid    1 size 4.55TiB used 728.53GiB path /dev/sdc
        devid    2 size 4.55TiB used 727.53GiB path /dev/sdd
        devid    3 size 4.55TiB used 729.01GiB path /dev/sde

```

This multidevice can be mounted with any of it's part devices. I could mount it with `mount /dev/sdc .`, `mount /dev/sdd .` and so on.

In my dashdot interface, the disks are more or less treated like seperate drives (see appendix 1&2). The first one shows how much the entire array stores, but the max capacity is that of a single drive. The other two are shown as empty drives.

It would be nice, if dashdot would notice them being a array and only displaying a single drive with the right capacities.

### Additional context

Appendix 1:
Disks in split view: page 1

![Screenshot_20230225_143053](https://user-images.githubusercontent.com/58274330/221359596-836b469a-2b81-4435-885c-d62515332aaa.png)

Appendix 2:
Disks in split view: page 2

![Screenshot_20230225_143406](https://user-images.githubusercontent.com/58274330/221359751-2ff5c71a-5ea1-4a06-bfd9-041e910f544e.png)

Appendix 3:
my docker-compose.yml

```yml
version: '3.5'
services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_PAGE_TITLE=homeserver.box - Dashboard
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_NETWORK_LABEL_LIST=type,speed_up,speed_down,interface_speed,public_ip
      - DASHDOT_OVERRIDE_OS=Debian GNU/Linux 11 (bullseye)
      - DASHDOT_OVERRIDE_ARCH=x86_64
    privileged: true
    ports:
      - 8001:3001
    volumes:
      - /:/mnt/host:ro
 ```

Notes:
The 3 last disks are identical, that's why they have the same name.

Dashdot runs in a docker container, the multidevice setup is done on the host. See Appendix 3.
