### ISSUE TITLE
[Bug] The command with DEFAULT_INTERFACE_PATH does produce an error.

### ISSUE THREAD

**Issue by Pryla** [MauriceNino/dashdot#61]
### Description of the bug

> After setting up your docker-compose.yml file, you have to run the following command to start the dashboard:
> 
> `DEFAULT_INTERFACE_PATH=$(readlink -f /sys/class/net/$(ip addr show | awk '/inet.*brd/{print $NF; exit}')) docker-compose up`

This command is producing this error: 

`**ERROR**: Volume /sys/devices/pci0000:00/0000:00:03.0/virtio0/net/eth0:/mnt/eth0 has incorrect format, should be external:internal[:mode]`

### How to reproduce

Set up the docker-compose file and run the given command.

### Relevant log output

```shell
`ERROR: Volume /sys/devices/pci0000:00/0000:00:03.0/virtio0/net/eth0:/mnt/eth0 has incorrect format, should be external:internal[:mode]`
```

### Where is your instance running?

Linux Server

### Additional context

It's running on a root server

**Comment by MauriceNino** [comment]
Can you post your full `docker-compose.yml` please?

**Comment by Pryla** [comment]
Yes sure:

```
version: '3.5'

# Config options can optionally set, by using the environment field.
# e.g:
#   environment:
#     DASHDOT_ENABLE_CPU_TEMPS: "true"

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '8002:3001' # port 8000 and 8001 are already occupied
    volumes:
      - /etc/os-release:/etc/os-release:ro
      - type: bind
        source: ${DEFAULT_INTERFACE_PATH}
        target: /mnt/eth0
```

Cheers :)
