### ISSUE TITLE
[Bug] Using "DASHDOT_ENABLE_CPU_TEMPS=true" gives a large error message (crashes the container)

### ISSUE THREAD

**Issue by vp-en** [MauriceNino/dashdot#706]
### Description of the bug

As the title says, enabling the environment `DASHDOT_ENABLE_CPU_TEMPS` makes my docker container go haywire.

### How to reproduce

I use this docker compose example:
```yaml
version: "3.9"

services:
  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    privileged: true
    labels:
     - "org.hotio.pullio.notify=true"
     - "org.hotio.pullio.update=true"
     - "org.hotio.pullio.generic.webhook=https://notifiarr.com/api/v1/notification/pullio/xxxxx-xxxxx-xxxxx-xxxx"
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_FS_VIRTUAL_MOUNTS=gcd-crypt:plex
      - DASHDOT_OVERRIDE_RAM_TYPE=DDR5
      - DASHDOT_DISABLE_INTEGRATIONS=true
    ports:
      - 3001:3001
    volumes:
      - /:/mnt/host:ro
    restart: unless-stopped
```

So I guess using that example, with the `DASHDOT_ENABLE_CPU_TEMPS` set to `true` makes it give the error mentioned down below.
It happens as soon as I try to load the webpage `http://ip.of.server:3001` or the reverse proxied url `https://dash.domain.com` - otherwise it just hangs if I use the `docker logs -tf dash` and monitor what's happening. It gets stuck after completing the speedtest - and then if I try and load the webpage, it gives the error message.

### Relevant log output

```shell
Posted the log here:

https://paste.ec/paste/6q3Vq2F4#YfDR+R0YqYAwBDZONFSq3dxY0pvsEajiBhKCp-Sl6Ht


Tried again after a reboot, since I added some entries into the `/etc/modules` to see if that helped - can't figure out if it's the same error or not:
https://paste.ec/paste/S8X1MfgW#wxTj8SyUFPcGyl6bYYqNGgrcYqUeNkPh-0E1Pb0ccnx
```

### Info output of dashdot cli

```shell
INFO
=========
Yarn: 1.22.19
Node: v18.15.0
Dash: 5.1.3

Cwd: /app
Hash: 386191c474baca48d35d655bf77a8b4953e8645b
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.17s.
```

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Linux Server

### Additional context

 I've added the correct things in my `/etc/modules` as well:
```
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.


# Generated by sensors-detect on Mon Apr 24 22:57:12 2023
# Chip drivers
coretemp
nct6775
```
