### ISSUE TITLE
[Bug] Dash. doesn't display widgets when features are enabled

### ISSUE THREAD

**Issue by t3b4n** [MauriceNino/dashdot#916]
### Description of the bug

I pasted the following settings in my docker compose file:

```
  # ----------------------------------------
  # DASH
  # ----------------------------------------
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '80:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_WIDGET_LIST: os, cpu, storage, ram, network, gpu
      DASHDOT_OS_LABEL_LIST: os, arch, up_since, dash_version
      DASHDOT_CPU_LABEL_LIST: brand, model, cores, threads, frequency
      DASHDOT_STORAGE_LABEL_LIST: brand, size, type
      DASHDOT_RAM_LABEL_LIST: brand,size,type,frequency
      DASHDOT_NETWORK_LABEL_LIST: type, speed_up, speed_down, interface_speed, public_ip
```

This caused Dash. to display only a white screen in the browser followed by these errors in the browser console:

![image](https://github.com/MauriceNino/dashdot/assets/5547916/1c8f32a4-40c4-4d01-ac8e-ffe47a28c99f)

In order to fix this, I had to remove features from the list. This is working fine:

```
  # ----------------------------------------
  # DASH
  # ----------------------------------------
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '80:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
```

### What browsers are you seeing the problem on?

Firefox, Safari

### Where is your instance running?

Linux Server

**Comment by MauriceNino** [comment]
Hi, I think the list is provided wrong. It needs to be a string list without spaces in between:

```
  # ----------------------------------------
  # DASH
  # ----------------------------------------
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '80:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network,gpu'
      # ...
```

Please let me know if that fixes your problem?
