### ISSUE TITLE
[Bug] Whitescreen when enabling Intel gpu with docker

### ISSUE THREAD

**Issue by DaGloaDone** [MauriceNino/dashdot#929]
### Description of the bug

Hello :)
First of all: Thank you so much for developing such an awesome Tool!
I Wang to integrate my intel gpu in the docker Container. I googled and it said i online have to Mount /dev/dri as Device. This works very well for other apps like Jellyfin and tdarr. But sadly not for dash..

My compose File:

```
version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '3001:3001'
    volumes:
      - /etc/os-release:/mnt/host/etc/os-release:ro
      - /:/mnt/host_data:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_WIDGET_LIST: 'os,storage,network,cpu,ram,gpu'
      
    devices:
      - /dev/dri:/dev/dri        
  ```

also one of my drives is not showing up correctly. It‘s 4 TB and only displayed as 900GB (same as the other HDD)

Thank you for your Help!
![F0CBF5AA-5637-408F-9A73-5CAFD22F7BD1](https://github.com/MauriceNino/dashdot/assets/29229081/78c7b653-d685-46d7-bb11-afcb6fa7a0cd)
