### ISSUE TITLE
Port configuration bug

### ISSUE THREAD

**Issue by defconxt** [MauriceNino/dashdot#948]
Unfortunately I'm unable to use this app as well due to not being able to change the ports, documentation is very misleading as well.

See: https://github.com/MauriceNino/dashdot
and
https://getdashdot.com/docs/install/docker-compose

It still shows to set 80:3001, switching the configuration to 8922:80 doesnt work and it ignores my request and instead successfully starts up and is listening on 3001 once I swapped the ports in the correct order. I have other services running on 3001.

```
2023-12-12T01:42:49.413014294Z yarn run v1.22.19
2023-12-12T01:42:49.444022840Z $ node .
2023-12-12T01:42:49.568110318Z listening on *:3001
```

Expectation: allow me to set my own host port, not be forced to use 3001

Result: not able.

_Originally posted by @defconxt in https://github.com/MauriceNino/dashdot/issues/945#issuecomment-1851176385_

**Comment by MauriceNino** [comment]
@defconxt - I think there is a misunderstanding on how Docker works. The port mapping just tells docker where to route to. There is no (good) way to read this from the application, that's why changing the internal port will not change the port that dash. listens to. This is by design, and I can't think of any other Docker container that would do that for you.

If you want to change the internal port (and I doubt that you really want to do that), you can use the configuration variable [DASHDOT_PORT](https://getdashdot.com/docs/config/features#dashdot_port). This will not solve any of your port conflicts though, as inside the container there is only one process running on one port anyways. You need to fix the internal port - e.g. `8922:3001`.

**Comment by MauriceNino** [comment]
The setting you just proposed (`8922:3001`) should work just fine. If there is a problem with that, it most likely has nothing to do with the ports.

I mean, no recommendation of an outside port would make sense anyway, because people might have occupied other ports as well. If you want to host multiple services with docker, you should have basic knowledge on how to do that, and that in turn should enable you to choose a valid port that is not already occupied. The error message you will get, if you choose an already occupied port, should give you enough information to fix it, or at least google it.

I don't think there is much to be changed in the documentation to make it more clear, but if you have any recommendations on what would have helped you, I am open to criticism.

Also, if you are running a reverse proxy on port 80 already, there is no need to forward ports from dash. at all. You can just expose them and then put them on the same network and route via container name/port. That's what I am doing with Traefik. The only ports exposed on my network (for web) are 80 and 443. Everything else gets routed internally.

Here is the configuration for the public demo, if that helps you:

```yml
version: "3.5"

services:
  server_dashboard:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    expose:
      - "3001"
    volumes:
      - /:/mnt/host:ro
    networks:
      - proxy_net
    environment:
      - DASHDOT_SHOW_DASH_VERSION=bottom_right
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dash.rule=Host(`dash.mauz.dev`)'
      - 'traefik.http.routers.dash.entrypoints=websecure'
      - 'traefik.http.routers.dash.tls.certresolver=myresolver'
```
